import { defineField, defineType } from 'sanity'

export const pageType = defineType({
  name: 'page',
  title: 'Generic Page',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Page Title',
      type: 'string',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'showInNav',
      title: 'Show in Navigation',
      type: 'boolean',
      description: 'If enabled, this page will appear in the main navigation menu',
      initialValue: true,
    }),
    defineField({
      name: 'isLocked',
      title: 'Lock Page (Members Only)',
      type: 'boolean',
      description: 'If enabled, this page will only be accessible to logged-in users.',
      initialValue: false,
    }),
    defineField({
      name: 'content',
      title: 'Page Content',
      type: 'array',
      of: [
        { type: 'heroBlock' },
        { type: 'brandBlock' },
        { type: 'pillarsBlock' },
        { type: 'benefitsBlock' },
        { type: 'mediaTextBlock' },
        { type: 'imageBlock' },
        { type: 'videoBlock' },
        { type: 'testimonialBlock' },
        { type: 'teamBlock' },
        { type: 'richTextBlock' },
        { type: 'ctaBlock' },
        { type: 'faqBlock' },
        { type: 'empathySectionBlock' },
        { type: 'highlightTextBlock' },
        { type: 'featureGridBlock' },
        { type: 'premiumFeaturesBlock' },
        { type: 'founderBioBlock' },
        { type: 'textCtaBlock' },
        { type: 'checklistBlock' },
        { type: 'introTextBlock' },
        { type: 'proseSectionBlock' },
        { type: 'twoColumnCompareBlock' },
        { type: 'spaceCardsBlock' },
        { type: 'pathChooserBlock' },
        { type: 'closingStatementBlock' },
      ],
    }),
  ],
})
