import { defineField, defineType } from 'sanity'

export const siteSettingsType = defineType({
    name: 'siteSettings',
    title: 'Site Settings',
    icon: () => '⚙️',
    type: 'document',
    groups: [
        { name: 'general', title: 'General', default: true },
        { name: 'footer', title: 'Footer' },
        { name: 'auth', title: 'Sign In / Sign Up' },
        { name: 'notFound', title: '404 Page' },
    ],
    fields: [
        // ── General ──
        defineField({
            name: 'title',
            title: 'Site Title',
            type: 'string',
            description: 'The name of your website (e.g. Flow in Faith).',
            initialValue: 'Flow in Faith',
            validation: (Rule) => Rule.required(),
            group: 'general',
        }),
        defineField({
            name: 'description',
            title: 'Site Description',
            type: 'text',
            description: 'Global description for SEO (Search Engine Optimization).',
            rows: 3,
            validation: (Rule) => Rule.required(),
            group: 'general',
        }),
        defineField({
            name: 'logo',
            title: 'Site Logo',
            type: 'image',
            options: { hotspot: true },
            group: 'general',
        }),
        defineField({
            name: 'favicon',
            title: 'Favicon',
            type: 'image',
            description: 'The small icon shown in browser tabs.',
            group: 'general',
        }),
        defineField({
            name: 'contactEmail',
            title: 'Primary Contact Email',
            type: 'string',
            validation: (Rule) => Rule.email(),
            group: 'general',
        }),
        defineField({
            name: 'secondaryEmail',
            title: 'Secondary Email (e.g. Collective)',
            type: 'string',
            validation: (Rule) => Rule.email(),
            group: 'general',
        }),
        defineField({
            name: 'websiteUrl',
            title: 'Website URL',
            type: 'url',
            description: 'Public-facing website URL shown in the footer.',
            group: 'general',
        }),
        defineField({
            name: 'socialLinks',
            title: 'Social Media Links',
            type: 'object',
            group: 'general',
            fields: [
                { name: 'instagram', title: 'Instagram URL', type: 'url' },
                { name: 'facebook', title: 'Facebook URL', type: 'url' },
                { name: 'youtube', title: 'YouTube URL', type: 'url' },
                { name: 'tiktok', title: 'TikTok URL', type: 'url' },
            ],
        }),

        // ── Footer ──
        defineField({
            name: 'tagline',
            title: 'Footer Tagline / Mission',
            type: 'text',
            rows: 3,
            description: 'Short mission statement displayed in the footer.',
            group: 'footer',
        }),
        defineField({
            name: 'copyrightText',
            title: 'Copyright Text',
            type: 'string',
            description: 'e.g. "Flow in Faith Teacher\'s Collective". The year is added automatically.',
            group: 'footer',
        }),
        defineField({
            name: 'footerQuickLinksLabel',
            title: '"Quick Links" Column Heading',
            type: 'string',
            group: 'footer',
        }),
        defineField({
            name: 'footerConnectLabel',
            title: '"Connect With Us" Column Heading',
            type: 'string',
            group: 'footer',
        }),
        defineField({
            name: 'footerSocialLabel',
            title: '"Follow us" Label',
            type: 'string',
            description: 'Text above the social icons (e.g. "Follow us on Social Media").',
            group: 'footer',
        }),
        defineField({
            name: 'memberLoginLabel',
            title: 'Member Login Button Text',
            type: 'string',
            description: 'Text shown on the footer login button for non-signed-in visitors.',
            group: 'footer',
        }),

        // ── Sign In / Sign Up ──
        defineField({
            name: 'signInHeading',
            title: 'Sign In Heading',
            type: 'string',
            description: 'e.g. "Welcome Back"',
            group: 'auth',
        }),
        defineField({
            name: 'signInSubtext',
            title: 'Sign In Subtext',
            type: 'string',
            description: 'e.g. "Sign in to access your Flow in Faith account"',
            group: 'auth',
        }),
        defineField({
            name: 'signUpHeading',
            title: 'Sign Up Heading',
            type: 'string',
            description: 'e.g. "Join Flow in Faith"',
            group: 'auth',
        }),
        defineField({
            name: 'signUpSubtext',
            title: 'Sign Up Subtext',
            type: 'string',
            description: 'e.g. "Create your account and become part of our community"',
            group: 'auth',
        }),

        // ── 404 Page ──
        defineField({
            name: 'notFoundHeading',
            title: '404 Heading',
            type: 'string',
            description: 'e.g. "Page Not Found"',
            group: 'notFound',
        }),
        defineField({
            name: 'notFoundMessage',
            title: '404 Message',
            type: 'string',
            description: 'e.g. "It seems you\'ve wandered off the path."',
            group: 'notFound',
        }),
        defineField({
            name: 'notFoundQuote',
            title: '404 Quote',
            type: 'text',
            rows: 2,
            description: 'Inspirational quote shown on the 404 page.',
            group: 'notFound',
        }),
        defineField({
            name: 'notFoundQuoteAttribution',
            title: '404 Quote Attribution',
            type: 'string',
            description: 'e.g. "Jeremiah 29:11"',
            group: 'notFound',
        }),
        defineField({
            name: 'notFoundHomeLabel',
            title: '404 Home Button Label',
            type: 'string',
            description: 'e.g. "Return Home"',
            group: 'notFound',
        }),
        defineField({
            name: 'notFoundSecondaryLabel',
            title: '404 Secondary Button Label',
            type: 'string',
            description: 'e.g. "Find a Teacher"',
            group: 'notFound',
        }),
        defineField({
            name: 'notFoundSecondaryLink',
            title: '404 Secondary Button Link',
            type: 'string',
            description: 'e.g. "/directory"',
            group: 'notFound',
        }),
    ],
})
